import { Download, Maximize2, Printer } from 'lucide-react'
import QRCode from 'qrcode'
import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Modal } from '../../components/Modal'
import { useEventData } from './useEventData'

export default function AdminQrCodesPage(){
  const {id}=useParams(); const {event,loading}=useEventData(id); const [codes,setCodes]=useState<{registration:string;attendance:string}>({registration:'',attendance:''}); const [large,setLarge]=useState<'registration'|'attendance'|null>(null)
  useEffect(()=>{ if(!event)return; const base=window.location.origin; Promise.all([QRCode.toDataURL(`${base}/evento/${event.slug}/inscricao`,{width:800,margin:2}),QRCode.toDataURL(`${base}/evento/${event.slug}/presenca`,{width:800,margin:2})]).then(([registration,attendance])=>setCodes({registration,attendance})) },[event])
  if(loading||!event)return <div className="admin-page">Carregando...</div>
  const save=(kind:'registration'|'attendance')=>{const a=document.createElement('a'); a.href=codes[kind]; a.download=`qr-${kind==='registration'?'inscricao':'presenca'}-${event.slug}.png`; a.click()}
  const print=(kind:'registration'|'attendance')=>{const w=window.open('','_blank');if(!w)return;w.document.write(`<html><body style="font-family:Arial;text-align:center;padding:40px"><h1>${kind==='registration'?'INSCRIÇÃO':'PRESENÇA'}</h1><h2>${event.name}</h2><img src="${codes[kind]}" style="width:520px;max-width:90vw"><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
  const cards:[string,'registration'|'attendance',string][]=[['QR Code de Inscrição','registration',`/evento/${event.slug}/inscricao`],['QR Code de Presença','attendance',`/evento/${event.slug}/presenca`]]
  return <div className="admin-page"><h1 className="admin-title">QR Codes</h1><p className="admin-subtitle">Use os códigos publicados no domínio final da Vercel nas artes.</p><div className="grid lg:grid-cols-2 gap-5 mt-7">{cards.map(([title,kind,path])=><div className="card" key={kind}><div className="flex justify-between items-start gap-4"><div><h2 className="font-extrabold text-[#04301D]">{title}</h2><p className="text-xs text-[#64756A] mt-1 break-all">{window.location.origin}{path}</p></div><span className={`badge ${kind==='attendance'?'badge-open':'badge-closed'}`}>{kind==='attendance'?'Presença':'Inscrição'}</span></div><div className="bg-[#f7faf5] rounded-2xl p-5 mt-5 grid place-items-center">{codes[kind]&&<img src={codes[kind]} className="w-[270px] max-w-full"/>}</div><div className="flex flex-wrap gap-2 mt-4"><button className="secondary-btn flex items-center gap-2" onClick={()=>setLarge(kind)}><Maximize2 size={15}/> Ampliar</button><button className="secondary-btn flex items-center gap-2" onClick={()=>save(kind)}><Download size={15}/> PNG</button><button className="secondary-btn flex items-center gap-2" onClick={()=>print(kind)}><Printer size={15}/> Imprimir</button></div></div>)}</div>{large&&<Modal title={large==='registration'?'QR Code de Inscrição':'QR Code de Presença'} onClose={()=>setLarge(null)}><div className="text-center"><img src={codes[large]} className="w-[430px] max-w-full mx-auto"/><p className="text-sm text-[#64756A] mt-4">{large==='attendance'?'Escaneie para registrar sua presença.':'Escaneie para realizar sua inscrição.'}</p></div></Modal>}</div>
}
